telefonicaid/iotagent-json

lib/iotagent-mqtt.js

Fix the different log type (JSON or Pipe) for the library and the IOTA log.

FIX Different log type in libraries and general logs

---

README.md

In certain MD-Renderers such as on Docker-Hub (https://hub.docker.com/r/telefonicaiot/iotagent-json/) these Anchor-Tags look very ugly.

Beautify README.MD to get rid of unnecessary <a ...> HTML-Anchor-Tags

---

package.json

https tends to work better in dockered environments.
Building the docker-container would otherwise require some ssh-key/trust acrobatics.

Use http for fetching git-repositories with npm instead of ssh

---

CHANGES_NEXT_RELEASE
npm-shrinkwrap.json
package.json
rpm/SPECS/iotajson.spec

Similar to PR https://github.com/telefonicaid/iotagent-json/pull/241
However, npm-shrinkwrap.json generation has been improved based in the following procedure
```
rm -rf node_modules
rm npm-shrinkwrap.json
npm install
npm shrinkwrap
```
executed in the reference CentOS 6 jenkins which used:
```
$ node --version
v4.8.4
$ npm --version
2.15.11
```

Step: 1.6.0-next -> 1.7.0

---

CHANGES_NEXT_RELEASE
lib/iotaUtils.js

Parameters for the MEASURE-001 error are passed using the wrong order, resulting on messages similar to the following ones:
```
Jun 16 10:03:19 ip-172-31-32-151 iotagent-json[20502]: time=2018-06-16T08:03:19.505Z | lvl=ERROR | corr=2c13365a-8d1b-4f23-b9ff-2ad5c119fbd4 | trans=2c13365a-8d1b-4f23-b9ff-2ad5c119fbd4 | op=IoTAgentMQTT.Utils | srv=n/a | subsrv=n/a | msg=MEASURES-001: Couldn't find device data for APIKey [LFLT] and DeviceId[1234] | comp=IoTAgent
Jun 16 10:03:19 ip-172-31-32-151 iotagent-json[20502]: time=2018-06-16T08:03:19.505Z | lvl=ERROR | corr=2c13365a-8d1b-4f23-b9ff-2ad5c119fbd4 | trans=2c13365a-8d1b-4f23-b9ff-2ad5c119fbd4 | op=IoTAgentJSON.MQTTBinding | srv=n/a | subsrv=n/a | msg=MEASURES-004: Device not found for topic [/1234/LFLT/attrs] | comp=IoTAgent
```
This small PR …

Fix parameter order for the MEASURE-001 error message

---

docs/installationguide.md
docs/operations.md
docs/stepbystep.md
docs/usermanual.md

After discussion with @dcalvoalonso 
With standard English usage, the “bound”  suffix in implies a direction e.g “Homeward bound" means "going **towards** my home”, therefore “Southbound” means "going **towards** the South”
In contrast, the phrase "to the North of” does not imply direction, it implies relative location — you can be to the North of a town, but travelling Southbound - i.e. towards the city.
The main common usage of Northbound/Southbound is found with motorway traffic reports e.g. “the Northbound carriageway is blocked"
Therefore the following usage is correct common English, and the existing documents should be corrected to use it: 
* Traffic **to the South of** the IoT Agent refers to the exchange of information and commands between a device and an IoT Agent (Native …

Clarified North/South, removed anchors, added code highlights

---

CHANGES_NEXT_RELEASE
package.json

1.7.0 is so older... 
2.18.3 should be our target version, but first we should check latest 1.X version (1.14.1)
This upgrade should be done in iotagent-ul also

[WIP] upgrade mqtt dep from 1.7.0 to 1.14.1

---

CHANGES_NEXT_RELEASE
package.json
rpm/SPECS/iotajson.spec

Similar to PR #273 (except npm-shrinkwrap.json generation, which is no longer include in repository)

Step: 1.7.0-next -> 1.8.0

---

docs/contribution.md
docs/installationguide.md
docs/operations.md
docs/stepbystep.md
docs/usermanual.md

* The ToC is suppressed with the ReadtheDocs CSS
* The ToC Header cannot be suppressed without CSS3
Therefore the title of the ToC should be removed to avoid confusion
* Add `bash` code hints where not found
Readthedocs can mis-diagnose code styles sometimes.
Related to telefonicaid/iotagent-node-lib/issues/648

Remove `##Index` from ToC since it is not required

---

test/unit/HTTP_reveice_measures-test.js
test/unit/MQTT_receive_measures-test.js
test/unit/amqpBinding-test.js
test/unit/configuration-api_test.js
test/unit/ngsiv2/HTTP_reveice_measures-test.js
test/unit/ngsiv2/MQTT_receive_measures-test.js
test/unit/ngsiv2/amqpBinding-test.js
test/unit/ngsiv2/configuration-api_test.js

FIX broken unit tests

---

.travis.yml
README.md
package.json

Expose Code Coverage results to Coveralls. Runs `npm test:coverage` after the unit tests and then sends the results to [coveralls](https://coveralls.io)
the repo needs to be exposed on coveralls as well (obviously) - see https://coveralls.io/repos/new
- SHOULD requirement from TSC

Add code coverage badge to README

---

CHANGES_NEXT_RELEASE
docs/installationguide.md
lib/bindings/MQTTBinding.js
lib/configService.js
package.json
test/unit/startup-test.js

This PR pretends to add support for using the mqtts transport. This PR also provides support for using client authentication using certificates and allows to configure whether or not allowing invalid (e.g. expired, self-signed, ...) certificates through the `rejectUnauthorized` option.
I have being using these changes with success, but it is true that this PR is currently not providing any unit tests, documentation... and probably it is not using the proper code style. Please, let me know whatever change is required to make this acceptable for inclusion 😃.

Improve MQTT client configurability (adding at least support for mqtts)

---

config.js
docker/Dockerfile
docker/README.md
docker/entrypoint.sh
docker/hooks/build

This is the second phase of the merge for PR https://github.com/telefonicaid/iotagent-json/pull/380. The diff +127 -5 is a good checksum ensuring that both PRs has the same content.
E2E CI testing will be done on this PR in order to guarantee nothing is broken. If tests are ok, then it will be merged.
CC: @Jagatjot @jason-fox @dcalvoalonso @AlvaroVega

Entry.sh file for username, password authentication in docker (second phase)

---

docker/README.md

This PR adds `IOTA_AUTH_CLIENT_ID` and  `IOTA_AUTH_CLIENT_SECRET` to the protected list.  Currently the `Dockerfile` **does support** them, but the existing version of iot-node-lib is missing the equivalent processing step. 
Related: https://github.com/telefonicaid/iotagent-node-lib/pull/767
Obviously assumes that a release with an updated `package.json` is imminent.

Add missing protected Sensitive Parameters.

---

CHANGES_NEXT_RELEASE
package.json
test/unit/ngsiv2/HTTP_commands_test.js
test/unit/ngsiv2/MQTT_commands_test.js
test/unit/ngsiv2/commandsAmqp-test.js
test/unit/ngsiv2/commandsPolling-test.js
test/unit/ngsiv2/contextRequests/pollingMeasure.json
test/unit/ngsiv2/contextRequests/updateCommand1.json
test/unit/ngsiv2/contextRequests/updateCommand3.json
test/unit/ngsiv2/contextRequests/updateStatus1.json
test/unit/ngsiv2/contextRequests/updateStatus2.json
test/unit/ngsiv2/contextRequests/updateStatus3.json
test/unit/ngsiv2/contextRequests/updateStatus4.json
test/unit/ngsiv2/contextRequests/updateStatus5.json
test/unit/ngsiv2/contextRequests/updateStatus6.json

This PR migrates the work done by PR #392 by @dcalvoalonso. In particular, it can be checked that:
* First commit 18adce6 has +984 -1 modifications and corresponds to PR #392 with +984 -1 (exact match)
* Second commit d97b7e1 is for setting the iotagent-node-lib branch to the one used in https://github.com/telefonicaid/iotagent-node-lib/pull/813
Commits beyond the second one are additional fixes.

Implements NGSIv2 context forwarding (from PR #392 with additions)

---

CHANGES_NEXT_RELEASE
lib/commonBindings.js

IMHO is not an error, its a client mitake.
twin PR https://github.com/telefonicaid/iotagent-ul/pull/416

log error -> log warn when device of apikey is not found

---

docker/README.md
docker/entrypoint.sh

Once Mongo-DB  User and Password are fully supported within the iot-node-lib, they should be made available obfuscated within Docker 
Related: https://github.com/telefonicaid/iotagent-node-lib/pull/852

Add AMPQ, MQTT and Mongo-DB User and Password as Docker Secrets

---

CHANGES_NEXT_RELEASE
lib/commonBindings.js
package.json

Fixed issue #426 for "Log always writes the same correlator and transaction id".

Fixed for iotagent-json issue #426

---

lib/commonBindings.js
lib/iotaUtils.js
lib/thinkingThingPlugin.js

Related https://github.com/telefonicaid/iotagent-node-lib/issues/963
Note: the `isCurrentNgsi()` can be removed once NGSI-v1 is dropped.

Replace checkNgsi2 with isCurrentNgsi

---

CHANGES_NEXT_RELEASE
config.js
docs/installationguide.md

fix https://github.com/telefonicaid/iotagent-json/issues/413
60 is default value for keepalive in python and nodejs mqtt libraries:
https://www.npmjs.com/package/mqtt#mqttclientstreambuilder-options

set 60 default keepalive mqtt value

---

.github/workflows/ci.yml
CHANGES_NEXT_RELEASE
docker/Dockerfile
docs/deprecated.md
package.json

With the recent release, Node 10 can be fully removed for the next release. No rush to merge this, just raising it whilst I remember to do it.

Fully Remove Node 10

---

lib/bindings/AMQPBinding.js
test/unit/amqpBinding-test.js
test/unit/amqpBinding-test2.js
test/unit/commandsAmqp-test.js
test/unit/ngsiv2/amqpBinding-test.js
test/unit/ngsiv2/amqpBinding-test2.js
test/unit/ngsiv2/commandsAmqp-test.js

Replace `new Buffer()` with `Buffer.from()` - see https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues
This is has been an issue from Node 10 onwards.

DeprecationWarning: Buffer() is deprecated due to security and usability issues.

---

CHANGES_NEXT_RELEASE
lib/iotaUtils.js

needs https://github.com/telefonicaid/iotagent-node-lib/pull/1002
for avoid raise a mongo alarm like
```
time=2021-03-11T08:01:17.133Z | lvl=DEBUG | corr=2efa0453-e1a4-4fbc-9009-b8428edf08fd | trans=2efa0453-e1a4-4fbc-9009-b8428edf08fd | op=IOTAUL.Common.Binding | from=n/a | srv=n/a | subsrv=n/a | msg=message topic: /kz8i86f13itd4ibff87secf8c/test1/attrs/v | comp=IoTAgent
time=2021-03-11T08:01:17.134Z | lvl=DEBUG | corr=2efa0453-e1a4-4fbc-9009-b8428edf08fd | trans=2efa0453-e1a4-4fbc-9009-b8428edf08fd | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["resource","apikey"] with queryObj {"resource":"/iot/d","apikey":"kz8i86f13itd4ibff87secf8c"} | comp=IoTAgent
time=2021-03-11T08:01:17.148Z | lvl=DEBUG | …
```

use get configuration silently

---

CHANGES_NEXT_RELEASE
lib/bindings/HTTPBinding.js

Twin of PR https://github.com/telefonicaid/iotagent-json/pull/554 (for master), porting the same fix for releases/1.17.0

add content-type header

---

CHANGES_NEXT_RELEASE
lib/iotaUtils.js

PR to fix the problems reported here https://github.com/telefonicaid/iotagent-ul/pull/493#discussion_r654531005
The problem is in NGSIv2, the value of results is different depending if it is triggered by: 
- Context Request (configuration|pollingInterval|publishInterval), having the following value: `{"type":"number","value":"200","metadata":{}},"publishInterval":{"type":"number","value":"80","metadata":{}}}`
- Context Notification (subscription|pollingInterval|publishInterval), having the following value: `[{"type":"string","value":"60","name":"pollingInterval"},{"type":"number","value":"600","name":"publishInterval"}]`

Fix: Processing configurations subscriptions in NGSIv2

---

test/unit/ngsiv2/config-test.js

After #567, the config test was changed from `FATAL` to `DEBUG` (here: https://github.com/telefonicaid/iotagent-json/pull/567/files#diff-32ba595ee3bda87b762afeb753381c650e3e1198af367953dd3b904a213ab849L48-R48). This introduced lot of "noise" on CI tests. This PR revert this change.

Fix NGSIv2 test logs

---

CHANGES_NEXT_RELEASE
lib/bindings/HTTPBinding.js

fix for https://github.com/telefonicaid/iotagent-json/issues/582
This PR uses accept header to build response content type for get commands

fix content-type for get command

---

CHANGES_NEXT_RELEASE
docs/usermanual.md
lib/iotagent-json.js
package.json

This PR handles sigint and adds a npm start script.
When a shutdown signal is sent, we need to do graceful shutdown out of Node.js and
express to avoid side effects. like finishing active requests before closing server, clean up resources, db connections etc.
see: https://stackfame.com/node-express-graceful-shutdown
There are no unit tests, but if you start the app from the command-line and `ctrl-c` you'll see the handler being called.

Add graceful shutdown

---

CHANGES_NEXT_RELEASE
lib/commonBindings.js
package.json
test/deviceProvisioning/provisionDeviceTimeinstant2.json

Instead of applying the `explicitAttr` filtering at the south port (i.e. to the measures being received by IOTA), move the filtering to the north port (i.e. at the point in which the CB update request is built). That way every measure/attribute will be available in calculations done by JELX expressions, but only the ones explicitly provisioned will pass to the CB.
see  https://github.com/telefonicaid/iotagent-node-lib/pull/1157#issuecomment-993711890
Part of https://github.com/telefonicaid/iotagent-node-lib/issues/1151

Remove preprocess stripping of explicitAttrs

---

test/unit/ngsiv2/commandsPolling-test.js

Removed old 'json:true' constructions present from legacy request library.
Related with https://github.com/telefonicaid/iotagent-node-lib/pull/1178

Remove JSON attribute from Request queries

---

CHANGES_NEXT_RELEASE
lib/commonBindings.js

fix for https://github.com/telefonicaid/iotagent-json/issues/642

check if procesedMesassure is an array of object, not just an array

---

CHANGES_NEXT_RELEASE
package.json

According with moment changelog between 2.27.0 to 2.29.2 there is only bugfixing
https://github.com/moment/moment/blob/develop/CHANGELOG.md
related https://github.com/telefonicaid/iotagent-node-lib/pull/1238

Update moment dep from 2.27 to 2.29.2 due to vulnerability

---

CHANGES_NEXT_RELEASE
lib/commonBindings.js

The logs where srv and subsrv are wrong is expected to be reproduced when a device has more than one geo:point attrs
time=2022-05-30T08:08:06.593Z | lvl=ERROR | corr=ef3f58df-8fda-480b-b15d-fb543396de40 | trans=ef3f58df-8fda-480b-b15d-fb543396de40 | op=IOTAJSON.HTTP.Binding | from=n/a | srv=smartcity | subsrv=/ | msg=MEASURES-002: Couldn't send the updated values to the Context Broker due to an error: {"name":"ENTITY_GENERIC_ERROR","message":"Error accesing entity data for device: device:disp6 of type: device","details":{"error":"NoResourcesAvailable","description":"You cannot use more than one geo location attribute when creating an entity. Use ignoreType metadata if you want to add additional informative locations."},"code":413} | comp=IoTAgent …

ensure context srv and subsrv using device srv and subsrv processing measures

---

CHANGES_NEXT_RELEASE
lib/bindings/MQTTBinding.js

fix for https://github.com/telefonicaid/iotagent-json/issues/679
This way, with default config, 5 tries for connect will be done before stop when an error of conection (ENOTFOUND, ECONNREFUSED or similar) is catched
Twin PR for UL agent is expected

 handle errors mqttt binding ending client

---

CHANGES_NEXT_RELEASE
package.json
test/unit/ngsiv2/HTTP_reveice_measures-test.js
test/unit/ngsiv2/HTTP_reveice_measures-test2.js
test/unit/ngsiv2/MQTT_commands_test.js
test/unit/ngsiv2/commandsAmqp-test.js
test/unit/ngsiv2/contextRequests/timeInstantMeasures.json
test/unit/ngsiv2/contextRequests/timeInstantMeasures2.json
test/unit/ngsiv2/contextRequests/timeInstantMeasures3.json
test/unit/ngsiv2/contextRequests/timestampAliasMeasure.json
test/unit/ngsiv2/contextRequests/timestampMeasure.json
test/unit/ngsiv2/contextRequests/timestampMeasure2.json
test/unit/ngsiv2/contextRequests/updateStatus2.json

PR to test agent with new iota node lib:
If timestamp is provided as measure then no metadata with timestamp is added to attributes.
Compression about timestamp is always checked in iotagent-node-lib, so always is uncompressed
iota-node-lib deb should be set to #master before merge

use node _lib refactor

---

test/unit/ngsiv2/HTTP_reveice_measures-test.js
test/unit/ngsiv2/contextRequests/timeInstantMeasuresB.json

Needs: https://github.com/telefonicaid/iotagent-node-lib/pull/1362
equivalent to:
```
{
"humidity":{
"type": "percent",
"value": "111222",
"metadata": {
"TimeInstant":{
"type": "DateTime",
"value": "+002020-02-22T22:22:22"
}
}
},
"TimeInstant":{
"type": "DateTime",
"value": "+002020-02-22T22:22:22"
}
}
```

split test response equivalent but with different order

---

CHANGES_NEXT_RELEASE
docs/usermanual.md
lib/commandHandler.js
test/deviceProvisioning/provisionCommand1.json
test/unit/ngsiv2/MQTT_commands_test.js
test/unit/ngsiv2/contextRequests/updateCommand4.json
test/unit/ngsiv2/contextRequests/updateCommand5.json
test/unit/ngsiv2/contextRequests/updateCommand6.json
test/unit/ngsiv2/contextRequests/updateStatus7.json
test/unit/ngsiv2/contextRequests/updateStatus8.json

This PR solves https://github.com/telefonicaid/iotagent-json/issues/716
It also adds: 
- tests for MQTT CMD expressions
- tests for MQTT CMD `payloadType` functionality
- Examples to `payloadType` doc

Add plain text `payloadType` command return option

---

CHANGES_NEXT_RELEASE
lib/bindings/HTTPBinding.js
test/unit/ngsiv2/MQTT_receive_measures-test2.js
test/unit/ngsiv2/contextRequests/singleMeasuresRawTypes.json
test/unit/ngsiv2/contextRequests/singleMeasuresRawTypes1.json

Fix for binary data representation when sending data through HTTP & MQTT

---

CHANGES_NEXT_RELEASE
lib/commonBindings.js

Update commonBindings.js: remove parsedMessageError

---

lib/bindings/HTTPBinding.js

related with contribution from PR https://github.com/telefonicaid/iotagent-json/pull/760

protect toString(hex)

---

CHANGES_NEXT_RELEASE
docs/usermanual.md
lib/bindings/HTTPBinding.js
package.json
test/unit/ngsiv2/HTTP_receive_measures-test3.js
test/unit/ngsiv2/contextRequests/singleMeasureSoapXml.json

Issue:  #759
solution adopted: Parse the XML into a JSON as the value of the measure (then rely un JEXL for further parsing)
For example: 
```
curl -i -X POST 'http://localhost:7897/iot/json/attrs/data?i=disp4&k=izc9cokegoy7kyfgdd6etipt6' -d '<soap:Envelope
xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
<soapenv:Header
xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"/>
<soapenv:Body
xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
<ns21:notificationEventRequest
xmlns:ns21="http://myurl.com">
<ns21:Param1>ABC12345</ns21:Param1>
<ns21:Param2/>
<ns21:Date>28/09/2023 11:48:15 +0000</ns21:Date>
<ns21:NestedAttr>
<ns21:SubAttr>This is a description</ns21:SubAttr>
</ns21:NestedAttr>
<ns21:Status>Assigned</ns21:Status>
<ns21:OriginSystem/>
</ns21:notificationEventRequest> …
```

 read measures in application/soap+xml content-type

---

docs/usermanual.md
lib/commonBindings.js
test/unit/ngsiv2/contextRequests/ngsildPayloadMeasure.json
test/unit/ngsiv2/contextRequests/ngsildPayloadMeasure2.json

Continuation of PR https://github.com/telefonicaid/iotagent-json/pull/779 to add `metadata` for `observedAt`, `createdAt`  and any other stuff found as ngsild attribute properties.

add metadata to ngsild payload measure + doc 

---

CHANGES_NEXT_RELEASE
lib/commonBindings.js
lib/constants.js
test/unit/ngsiv2/contextRequests/ngsildPayloadMeasure.json
test/unit/ngsiv2/contextRequests/ngsildPayloadMeasure2.json
test/unit/ngsiv2/contextRequests/ngsiv2PayloadMeasure.json
test/unit/ngsiv2/contextRequests/ngsiv2PayloadMeasure2.json

Given a ngsiv2 measure like:
```
curl -i -X POST 'http://localhost:7897/iot/json?i=test1&k=bryippqcmkxc8ncguqxejibts' -d'{
"actionType": "append",
"entities": [
{
"id": "urn:ngsiv2:Streetlight:Streetlight-Mylightpoint-2",
"type": "Streetlight",
"name": {
"type": "Text",
"value": "MyLightPoint-test1"
}
}
]
}' -H 'content-type: application/json'
```
id and type from entity ( "id": "urn:ngsiv2:Streetlight:Streetlight-Mylightpoint-2" and  "type": "Streetlight",) are progressing as measures to iotagent using prefix ngsiv2_id and ngsiv2_type respectively:
```
"ngsi_id": {
"type": "string",
"value": "urn:ngsiv2:Streetlight:Streetlight-Mylightpoint-2"
},
"ngsi_type": {
"type": "string",
"value": "Streetlight"
},
```

Task/include entity id and entity type as measures for ngsi  measures 

---

CHANGES_NEXT_RELEASE
Changelog
package.json

Task/prepare 3.2.0

---

CHANGES_NEXT_RELEASE
lib/bindings/HTTPBinding.js
lib/commonBindings.js
test/unit/ngsiv2/HTTP_receive_ngsild_measures-test.js
test/unit/ngsiv2/HTTP_receive_ngsiv2_measures-test.js
test/unit/ngsiv2/HTTP_reveice_measures-test2.js
test/unit/ngsiv2/MQTT_receive_ngsiv2_measures-test.js
test/unit/ngsiv2/contextRequests/multipleMeasuresJsonTypes3.json
test/unit/ngsiv2/contextRequests/ngsildPayloadMultipleMeasure.json
test/unit/ngsiv2/contextRequests/ngsiv2PayloadMultipleMeasure.json
test/unit/ngsiv2/contextRequests/ngsiv2PayloadMultipleMeasure2.json
test/unit/ngsiv2/contextRequests/timeInstantMultipleMeasures.json
test/unit/ngsiv2/contextRequests/timeInstantMultipleMeasures1b.json
test/unit/ngsiv2/contextRequests/unprovisionedDeviceMultiple.json

fix for https://github.com/telefonicaid/iotagent-json/issues/825
and needs https://github.com/telefonicaid/iotagent-node-lib/pull/1607

send update for multiple measures

---

CHANGES_NEXT_RELEASE
Changelog
docs/usermanual.md
lib/bindings/HTTPBinding.js
lib/constants.js

https://github.com/telefonicaid/iotagent-node-lib/issues/1650
Usage: 
$ curl -i -X POST 'http://localhost:7897/iot/json?i=disp1&k=APIKEY1' -d '{ "level": "33"}' -H 'content-type: application/json'
HTTP/1.1 200 OK
X-Powered-By: Express
**X-Processing-Time: 38** 
Content-Type: application/json; charset=utf-8
Content-Length: 2
ETag: W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8"
Date: Thu, 26 Sep 2024 11:28:57 GMT
Connection: keep-alive
Keep-Alive: timeout=5

add response time procesing header

---

test/unit/ngsiv2/HTTP_receive_ngsiv2_measures-test.js
test/unit/ngsiv2/contextRequests/ngsiv2PayloadMeasureTimeInstant.json

~~related and needs https://github.com/telefonicaid/iotagent-node-lib/pull/1672~~
This example only relies on device/group payloadType, which should be defined as "ngsiv2" for this case as https://github.com/telefonicaid/iotagent-json/blob/b00d69d64b1bb4c431b4e1724b69081b3256803d/test/unit/ngsiv2/deviceProvisioning/provisionDeviceHTTP2.json#L10

add test about ngsiv2 measure with TimeInstant

---

test/functional/config-test.js
test/unit/ngsiv2/HTTP_reveice_measures-test.js
test/unit/ngsiv2/contextRequests/unprovisionedStoreLastMeasure.json

This PR adds a full test for branch https://github.com/telefonicaid/iotagent-node-lib/pull/1670

add tests about last measure

---

CHANGES_NEXT_RELEASE
lib/configService.js

The value of the following iotagent env vars were not printed at iotagent startup:
'IOTA_CONFIG_RETRIEVAL',
'IOTA_DEFAULT_KEY',
'IOTA_DEFAULT_TRANSPORT'
Just print them. 
Less than a minor bug.

just print values for that env vars

---

CHANGES_NEXT_RELEASE
lib/bindings/HTTPBinding.js
test/unit/ngsiv2/config-test.js

related: https://github.com/telefonicaid/iotagent-json/pull/852

Use config.defaultTransport instead of 'HTTP'

---

CHANGES_NEXT_RELEASE
lib/bindings/HTTPBinding.js
test/unit/ngsiv2/HTTP_commands_test.js

Bug introduced by https://github.com/telefonicaid/iotagent-json/pull/794

fix check endpoint expression for http commands

---

CHANGES_NEXT_RELEASE
lib/commonBindings.js
test/unit/ngsiv2/MQTT_receive_measures-test2.js
test/unit/ngsiv2/MQTT_receive_ngsild_measures-test.js
test/unit/ngsiv2/MQTT_receive_ngsiv2_measures-test.js
test/unit/ngsiv2/amqpBinding-test2.js
test/unit/ngsiv2/contextRequests/multipleMeasure3.json
test/unit/ngsiv2/contextRequests/multipleMeasureAMQP4.json
test/unit/ngsiv2/contextRequests/multipleMeasuresJsonTypes4.json
test/unit/ngsiv2/contextRequests/ngsildPayloadMeasure3.json
test/unit/ngsiv2/contextRequests/ngsiv2PayloadMeasure3.json
test/unit/ngsiv2/contextRequests/timestampMeasure3.json
test/unit/ngsiv2/contextRequests/unknownMeasures3.json
test/unit/ngsiv2/contextRequests/unprovisionedDevice4.json

related https://github.com/telefonicaid/iotagent-json/pull/826 and https://github.com/telefonicaid/iotagent-json/issues/856

send multiple MQTT measures in a batch update to CB

---

CHANGES_NEXT_RELEASE
Changelog
lib/commonBindings.js
test/unit/ngsiv2/MQTT_receive_measures-test.js
test/unit/ngsiv2/contextRequests/singleArrayMeasure2.json

Allow single array measures of 1 element not handled like single mesures
Fix for issue https://github.com/telefonicaid/iotagent-json/issues/856#issuecomment-2621436103

Allow single array MQTT measures of 1 element handed like array

---

docs/usermanual.md

Update usermanual.md about expressions in commands:

---

CHANGES_NEXT_RELEASE
config.js
docs/installationguide.md
lib/bindings/MQTTBinding.js
lib/configService.js
package.json
test/unit/ngsiv2/MQTT_commands_test.js
test/unit/ngsiv2/MQTT_get-configuration_test.js

Issue: https://github.com/telefonicaid/iotagent-json/issues/875
After merged it. I'll create same PR against to [telefonicaid/iotagent-ul](https://github.com/telefonicaid/iotagent-ul).

Fix: Subscription fails on AWS IoT Core broker 
