- CHANGES_NEXT_RELEASE
- lib/errors.js
- lib/iotagent-mqtt.js
- test/deviceProvisioning/provisionConfiguration1.json
- test/unit/configuration-api_test.js
> ADD Support for configuration groups

- CHANGES_NEXT_RELEASE
- README.md
- lib/iotagent-mqtt.js
- test/unit/receive_measures-test.js
> FIX Agent crashes with invalid JSON

- package.json
> Prepare for next release

- CHANGES_NEXT_RELEASE
- lib/iotagent-mqtt.js
- lib/timestampProcessPlugin.js
- package.json
- test/contextRequests/timestampAliasMeasure.json
- test/deviceProvisioning/provisionDevice2.json
- test/unit/attribute-alias_test.js
> FIX Attribute alias working with timestamps

- CHANGES_NEXT_RELEASE
- lib/thinkingThingPlugin.js
- test/contextRequests/TTModuleC1.json
> FIX C1 should be renamed to P1

- CHANGES_NEXT_RELEASE
- bin/iotaMqttTester.js
- package.json
> ADD Generic IOTA command line functions

- package.json
Fix the dependencies in the package.json
> ADD Fixed dependencies

- CHANGES_NEXT_RELEASE
- README.md
- lib/iotagent-mqtt.js
> ADD Password credentials for the agent

- CHANGES_NEXT_RELEASE
- bin/iotagentMqtt.js
> FIX IOTA Version doesnt show in about option

- README.md
Change the configuration command description and add a right example.
> FIX Documentation

- CHANGES_NEXT_RELEASE
- lib/iotagent-mqtt.js
- test/unit/configuration-api_test.js
> FIX mandatory resource must be equal to the configured IOTAM resource

- CHANGES_NEXT_RELEASE
- lib/iotagent-mqtt.js
> FIX Hour format

- CHANGES_NEXT_RELEASE
- README.md
- config.js
- lib/iotagent-mqtt.js
- test/config-test.js
> ADD TT Plugin documentation

- CHANGES_NEXT_RELEASE
- lib/constants.js
- lib/iotagent-mqtt.js
> ADD Constants to constant file

- CHANGES_NEXT_RELEASE
- lib/iotagent-mqtt.js
> Use wildcards instead of explicit registrations for topic subscription

- lib/iotagent-mqtt.js
- test/config-test.js
- test/unit/configuration-api_test.js
Fix the default resource location (that changed from the IoTManager object to the main iota object in last version of the library).
> FIX Default resource location

- CHANGES_NEXT_RELEASE
- lib/commandHandler.js
- lib/configService.js
- lib/iotagent-json.js
> ADD Config service for internal configuration

- lib/iotagent-json.js
- test/deviceProvisioning/provisionConfiguration1.json
> FIX Default resource not used

- CHANGES_NEXT_RELEASE
- README.md
- lib/configService.js
- test/config-startup.js
- test/unit/startup-test.js
- test/unit/subscription-management_test.js
> ADD Environment variable configuration

- lib/constants.js
- lib/iotagent-json.js
- test/unit/attribute-alias_test.js
- test/unit/configuration-api_test.js
- test/unit/receive_measures-test.js
- test/unit/subscription-management_test.js
- test/unit/supportThinkingThingModules_test.js
Fixes https://github.com/telefonicaid/iotagent-node-lib/issues/361
> Change the measure topics to be homogeneous with other IOTAs

- CHANGES_NEXT_RELEASE
- README.md
- lib/configService.js
- test/unit/startup-test.js
> FIX Add environment variable prefix

- lib/iotagent-json.js
- test/contextRequests/updateStatus2.json
Add Event plugin for the JSON Iota
> ADD Event plugin

- rpm/SOURCES/etc/init.d/iotajson
Fijado error cuando la instancia no se encontraba y además añadido mensaje.
> added error message when instance is not found

- npm-shrinkwrap.json
- package.json
> Prepare next release

- config.js
Just like https://github.com/telefonicaid/iotagent-ul/blob/master/config.js
> add mongodb conf as uiotagent ul conf

- npm-shrinkwrap.json
- package.json
Update bugfix version of IoTA Lib
> Update bugfix version of IoTA Lib

- CHANGES_NEXT_RELEASE
- README.md
- docs/operations.md
- lib/bindings/HTTPBinding.js
- lib/bindings/MQTTBinding.js
- lib/commandHandler.js
- lib/configService.js
- lib/iotaUtils.js
- lib/iotagent-json.js
- lib/thinkingThingPlugin.js
- lib/timestampProcessPlugin.js
- lib/transportSelector.js
- test/unit/configuration-api_test.js
Twin of PR #171 
Also fixes #173
> Cherry-pick operations manual

- .travis.yml
- package.json
> Colapsing develop into master

- rpm/SOURCES/etc/init.d/iotajson
Para evitar parchear el script de inicio en los Ansible de despliegue
> corregido usuario y añadidas opciones para preservar variables de entorno

- CHANGES_NEXT_RELEASE
- lib/iotagent-json.js
- test/unit/MQTT_commands_test.js
> ADD Multientity and transformation plugins

- CHANGES_NEXT_RELEASE
- lib/iotagent-json.js
> ADD Timestamp plugin

- Dockerfile
We do not have a section for docker docs (in installationguide).
Which text can be added?
> optimize docker and select node version

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBinding.js
- lib/bindings/MQTTBinding.js
- lib/commandHandler.js
- lib/iotaUtils.js
> FIX Missing context entries in logging statements

- CHANGES_NEXT_RELEASE
- docs/usermanual.md
- lib/bindings/HTTPBinding.js
> FIX Bug retrieveing polling commands

- docs/stepbystep.md
I believe the default context broker port is 1026.
> Update context broker port to 1026 in stepbystep page.

- docs/operations.md
> added a severity field

- npm-shrinkwrap.json
- rpm/SPECS/iotajson.spec
Add npm-shrinkwrap.json file in master branch and adjust .spec to take it into account at RPM generation time.
@vgarciag
> FIX shrinkwrap aspects

- CHANGES_NEXT_RELEASE
- npm-shrinkwrap.json
- package.json
- rpm/SPECS/iotajson.spec
Reference commit https://github.com/telefonicaid/iotagent-json/commit/9b0f0e91c5a8851d5c037d9973dfcaede6431aef to check steps. The  npm-shrinkwrap.json changes are new.
> ADD Step 1.5.0 -> 1.6.0-next

- config.js
- docs/index.md
- docs/stepbystep.md
The main goal of this PR is to bring a solution to the issue #222. I.e, fixing the stepbystep, making it usable for the new users. The scope of the issue is huge because there are many things to be fixed. Thus, I've had to limit the scope of this PR to the first 2 sections of the stepbystep ("Introduction" and 
"Provisioning a single device with the default API Key").
This PR focus:
- fixes the main showstopper mentioned in #222
As bonus:
- closes #232 
- fixes 5 of the items in #216
> Fix stepbystep.md (Part 1)

- package.json
Reverts telefonicaid/iotagent-json#253
> Revert "Use http for fetching git-repositories with npm instead of ssh"

- package.json
Reverts telefonicaid/iotagent-json#254
> Revert "Revert "Use http for fetching git-repositories with npm instead of ssh""

- CHANGES_NEXT_RELEASE
- config.js
- lib/bindings/HTTPBinding.js
- lib/commandHandler.js
- lib/commonBindings.js
- lib/iotaUtils.js
- test/config-startup.js
- test/config-test.js
- test/unit/HTTP_reveice_measures-test.js
- test/unit/commandsAmqp-test.js
Fix issue:  https://github.com/telefonicaid/iotagent-json/issues/257
including HTTP and MQTT binding
> fix transport in autoprovision device depending on binding

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBinding.js
- test/unit/commandsPolling-test.js
issue: https://github.com/telefonicaid/iotagent-json/issues/256
> allow empty payload for getCmd

- lib/bindings/HTTPBinding.js
isssue: https://github.com/telefonicaid/iotagent-json/issues/266
> fix lint issues

- npm-shrinkwrap.json
- package.json
> Step: 1.7.0 -> 1.7.0-next

- CHANGES_NEXT_RELEASE
- config.js
- docs/installationguide.md
- lib/bindings/MQTTBinding.js
- lib/configService.js
issue: https://github.com/telefonicaid/iotagent-json/issues/279
> enable qos and retain in mqtt

- lib/bindings/MQTTBinding.js
- npm-shrinkwrap.json
> check boolean field against boolean value

- npm-shrinkwrap.json
Reverts telefonicaid/iotagent-json#291
> Revert "update npm-shrinkwrap.json"

- CHANGES_NEXT_RELEASE
- config.js
- docs/installationguide.md
- lib/bindings/AMQPBinding.js
- lib/configService.js
- test/config-startup.js
- test/config-test.js
fix issue https://github.com/telefonicaid/iotagent-json/issues/297
> add and use AMQP env vars

- docs/installationguide.md
- lib/bindings/AMQPBinding.js
- lib/configService.js
- lib/constants.js
> add amqp retry conf

- CHANGES_NEXT_RELEASE
- Dockerfile
- docs/installationguide.md
The provided solution has demonstrated to work correctly under the same conditions used to reproduce bug #336.
Please find attached some screenshots for a test of 3,5 hours.
> Fixes bug #336

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
Merge after PR https://github.com/telefonicaid/iotagent-node-lib/pull/669
> use group timestamp conf

- .dockerignore
- Dockerfile
* Save `Dockerfile` as UTF-8 - to correct the `MAINTAINER`  Telefónica I+D
* Add `.dockerignore` file
* Use an `ARG` to set the node version
> Minor Dockerfile fix

- CHANGES_NEXT_RELEASE
- config.js
- docs/installationguide.md
- lib/bindings/HTTPBinding.js
- lib/configService.js
> Timeout for HTTP commands

- README.md
Training materials have been identified and added to the Academy
> Add Academy Link - Fix #368

- test/unit/ngsiv2/HTTP_reveice_measures-test.js
- test/unit/ngsiv2/MQTT_receive_measures-test.js
- test/unit/ngsiv2/amqpBinding-test.js
- test/unit/ngsiv2/attribute-alias_test.js
- test/unit/ngsiv2/configuration-api_test.js
- test/unit/ngsiv2/subscription-management_test.js
- test/unit/ngsiv2/supportThinkingThingModules_test.js
Please @dcalvoalonso have a look.
> FIX broken unit test due to mock failing with ?type expecations

- README.md
- docs/roadmap.md
Fixes https://github.com/telefonicaid/iotagent-json/issues/379
@dcalvoalonso could you have a look and provide LGTM if ok, pls? Thanks!
> Add roadmap

- docker/Dockerfile
JSON Agent Equivalent of https://github.com/telefonicaid/iotagent-ul/pull/342
> Expose Ports

- CREDITS
Fixes issue #373
Based in the draft at https://github.com/telefonicaid/iotagent-json/pull/386 by @M0nikaSharma
CC: @AlvaroVega @dcalvoalonso @dmoranj
> Create  CREDITS file

- config.js
- docker/Dockerfile
- docker/README.md
- docker/entrypoint.sh
- lib/configService.js
> Entry.sh file for username, password authentication in docker

- docker/Dockerfile
@jason-fox could you check alignment with Dockerfile in other IOTAs and provide LGTM, pls? Thanks!
> FIX comment in Dockerfile to align with other IOTAs

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> Step: 1.9.0-next -> 1.10.0

- CHANGES_NEXT_RELEASE
- lib/bindings/MQTTBinding.js
- lib/configService.js
- lib/constants.js
- package.json
- test/unit/startup-test.js
- test/unit/subscription-management_test.js
twin https://github.com/telefonicaid/iotagent-ul/pull/367
> reconnect mqtt if close

- config.js
- docs/installationguide.md
fix https://github.com/telefonicaid/iotagent-json/issues/417
No CNR update
> update MQTT doc

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> Step: 1.10.0-next -> 1.11.0

- CHANGES_NEXT_RELEASE
- lib/bindings/MQTTBinding.js
To avoid error:
Ignoring: TypeError: callback is not a function
> check callback before use it

- CHANGES_NEXT_RELEASE
- lib/bindings/AMQPBinding.js
- lib/bindings/MQTTBinding.js
- lib/iotagent-json.js
Updating files for [Issue#409](https://github.com/telefonicaid/iotagent-json/issues/409)
> Fixing of AMQP and MQTT connection (issue#409)

- CHANGES_NEXT_RELEASE
- bin/iotagent-json
- config.js
- docker/README.md
- docs/installationguide.md
- docs/limits.conf
- docs/sysctl.conf
- lib/iotagent-json.js
- package.json
@fgalan 
- Modify the IoTAgent-json to deal with the option multi-thread.
- Correct bug about accessing configuration data of MQTT with not defined MQTT.
- Add the corresponding new variable in the config.js (multiCore) with description.
- Change in the Readme.md (Docker) and Installation Guide regarding High Performance execution of the IoT Agent - JSON.
- Create 2 examples files of the user limits and sysctl configuration for high performance execution.
Unit tests, E2E tests in single-thread (legacy options) and multi-thread:
- Obtain IoT Agent JSON version info
- Provisioning Service
- Retrieve Service
- Provisioning Device
- Retrieve all devices
- Retrieve 1 device
- Send Measurement (*5)
- (Orion) Get list of entity types
- (Orion) Get list of entities
- (Orion) Get measurement
- …
> Integration of the multithreading functionality of the IoT Agent Node Lib into the IoT Agent - JSON

- test/unit/ngsiv2/bidirectionalityHttp-test.js
- test/unit/ngsiv2/subscriptions/bidirectionalSubscriptionRequest.json
Related with telefonicaid/iotagent-node-lib#822
> FIX broken utest after telefonicaid/iotagent-node-lib#822

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/419
> STep: 1.11.0-next -> 1.12.0

- package.json
> Step: 1.12.0 -> 1.12.0-next

- docs/installationguide.md
Related with issue #455 
@filgiuff it would be great if you can have a look and provide LGTM if you find the comment ok.
> ADD comment about keepalive in documentation

- CHANGES_NEXT_RELEASE
- docs/usermanual.md
Issue #391 
This PR is a complement to PR #396 . To be merged after that one.
Please, @Chandradeep-NEC have a look and provide feedback. If you find something wrong or something that needs to be added, please tell me. Thanks
> ADD multimeasure documentation

- CHANGES_NEXT_RELEASE
- config.js
- docs/installationguide.md
- lib/bindings/HTTPBinding.js
- lib/bindings/MQTTBinding.js
- lib/configService.js
- test/unit/startup-test.js
Align HTTP processing with changes previously made in the Ultralight Agent.
- cert, key (retrieved from files).
- add missing options to config
- update documentation.
> Add Southbound HTTPS support

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> Step: 1.13.0-next -> 1.14.0

- CHANGES_NEXT_RELEASE
- config.js
- lib/commonBindings.js
- package.json
- test/deviceProvisioning/provisionDeviceTimeinstant2.json
- test/unit/ngsiv2/HTTP_reveice_measures-test.js
- test/unit/ngsiv2/contextRequests/timeInstantMeasures2.json
- test/unit/ngsiv2/contextRequests/timeInstantMeasures3.json
> updated src and UT files for implementation of "selectively ignore some measure"

- CHANGES_NEXT_RELEASE
- config.js
- docs/installationguide.md
- lib/bindings/MQTTBinding.js
- lib/commonBindings.js
- lib/configService.js
- lib/constants.js
- test/unit/MQTT_receive_measures-test.js
Same as https://github.com/telefonicaid/iotagent-ul/pull/429
> Leading slashes mqtt topics

- docs/stepbystep.md
- docs/usermanual.md
- lib/errors.js
Updated document and error.js file regards issue sleepTime value error #224
> Updated document and error.js file regards issue #224

- CHANGES_NEXT_RELEASE
- lib/commonBindings.js
fix issue https://github.com/telefonicaid/iotagent-json/issues/486
> Update commonBindings.js: fix evaluation of parseMessage 

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
related with https://github.com/telefonicaid/iotagent-node-lib/pull/891
needs https://github.com/telefonicaid/iotagent-node-lib/pull/896
> get device silently

- CHANGES_NEXT_RELEASE
- lib/bindings/MQTTBinding.js
from https://github.com/telefonicaid/iotagent-json/issues/500
Twin PR for iotagent-ul expected
> Log as info command and conf request

- lib/iotaUtils.js
continuation of thread https://github.com/telefonicaid/iotagent-json/pull/502 issue https://github.com/telefonicaid/iotagent-json/issues/500
> check ngsi to process response

- CHANGES_NEXT_RELEASE
- docs/usermanual.md
- lib/bindings/MQTTBinding.js
related https://github.com/telefonicaid/iotagent-node-lib/pull/925
needs PR https://github.com/telefonicaid/iotagent-node-lib/pull/925
> check first and use mqtt {retain, qos} properties from command in command execution

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> step 1.15.0-next -> 1.16.0

- .textlintrc
- package.json
Fix for problem described on https://github.com/telefonicaid/iotagent-json/pull/515
> FIX no-dead-links error on Lint Markdown GitHub Action

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> step 1.16.0-next -> 1.17.0

- package.json
>  Step: 1.17.0 -> 1.17.0-next

- README.md
Updated README file. 
Pending https://github.com/telefonicaid/iotagent-json/pull/534 to fulfil all the requirements for the badge
> Adding CII Best Practices Badge to README.md

- docs/contribution.md
Improving contribution guidelines for developers to align with CII Best Practices requirements
> Updating contribution file

- CHANGES_NEXT_RELEASE
- docs/usermanual.md
- lib/configService.js
Equivalent of https://github.com/telefonicaid/iotagent-ul/pull/474
> Add protected variables

- package.json
- rpm/SPECS/iotajson.spec
relies on https://github.com/telefonicaid/iotagent-node-lib/pull/1015/
> Step: 1.17.0 -> 1.17.1

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBinding.js
> add content-type header

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
Mimics (although not exactly the same) PR https://github.com/telefonicaid/iotagent-json/pull/540
> Step: 1.17.1 -> 1.17.2

- test/unit/ngsiv2/MQTT_receive_measures-test.js
- test/unit/ngsiv2/MQTT_receive_measures-test2.js
- test/unit/ngsiv2/commandsAmqp-test.js
Updating NGSI V2 Unit tests with cases included on NGSI V1 before deleting them
> Complete NGSIV2 Unit tests

- CHANGES_NEXT_RELEASE
- package.json
> Upgrade underscore dep (1.9.1 to 1.12.1)

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> Step: 1.17.0-next -> 1.18.0

- lib/commonBindings.js
> simplify check

- package.json
> Step: 2.19.0 -> 2.19.0-next

- CHANGES_NEXT_RELEASE
- lib/commonBindings.js
twin PR of https://github.com/telefonicaid/iotagent-ul/pull/512
> fix service and subservice when apikey is not found

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> Step: 1.19.0-next -> 1.20.0

- package.json
> Step: 2.20.0 -> 2.20.0-next

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1155
> provide device type to findCOnfiguration to achieve a better group match

- lib/bindings/MQTTBinding.js
issue https://github.com/telefonicaid/iotagent-json/issues/610
no CNR update is needed
> log as info subscribed topics

- lib/commonBindings.js
Implementing issue https://github.com/telefonicaid/iotagent-json/issues/618
No need of CNR entry (already covered by the entries about the new functionality for binary parsing)
> FIX simplify parseMessage

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/597
> Step: 1.20.0-next -> 1.21.0 

- docs/usermanual.md
Twin PR https://github.com/telefonicaid/iotagent-ul/pull/536
>  FIX improve command protocol details

- CHANGES_NEXT_RELEASE
- docs/usermanual.md
- lib/bindings/MQTTBinding.js
- package.json
fix for https://github.com/telefonicaid/iotagent-json/issues/650
> fix command mqtt qos value and ensure mqtt clientid unique

- package.json
Misses in PR https://github.com/telefonicaid/iotagent-json/pull/656
> FIX package.json version

- package.json
>  step 1.22.0 -> 1.22.0-next

- CHANGES_NEXT_RELEASE
- lib/commandHandler.js
- test/deviceProvisioning/provisionCommandHTTP.json
- test/deviceProvisioning/provisionCommandHTTP2.json
- test/unit/ngsiv2/HTTP_commands_test.js
issue related https://github.com/telefonicaid/iotagent-json/issues/634
> include id, type, service and subservice in ctxt for evaluate expresion in command

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBinding.js
- test/unit/ngsiv2/contextRequests/updateProvisionDeviceCommandHttp.json
- test/unit/ngsiv2/deviceProvisioning/updateProvisionDeviceCommandHttp.json
issue https://github.com/telefonicaid/iotagent-json/issues/670
expression will be in device.endpoint or in another field (i.e. device.endpoint_exp) ?
> allow apply expression to device http.endpoint

- package.json
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/658
> step 2.23.0 -> 2.23.0-next

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> Step: 1.24.0-next -> 1.25.0

- package.json
> Step: 1.25.0 -> 1.25.0-next

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
- test/groupProvisioning/provisionFullGroupAMQP.json
- test/unit/ngsiv2/HTTP_reveice_measures-test.js
- test/unit/ngsiv2/HTTP_reveice_measures-test2.js
- test/unit/ngsiv2/MQTT_receive_measures-test.js
- test/unit/ngsiv2/MQTT_receive_measures-test2.js
- test/unit/ngsiv2/amqpBinding-test.js
- test/unit/ngsiv2/explicit_attributes-test.js
related and needs https://github.com/telefonicaid/iotagent-node-lib/pull/1275
> use group apikey for autoprovision device

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/686
> Step: 1.25.0-next -> 1.26.0

- package.json
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/687
> Step: 1.26.0 -> 1.26.0-next

- package.json
> Step: 2.0.0 -> 2.0.0-next

- CHANGES_NEXT_RELEASE
- test/unit/ngsiv2/contextRequests/timeInstantMeasures.json
- test/unit/ngsiv2/contextRequests/timeInstantMeasures2.json
- test/unit/ngsiv2/contextRequests/timeInstantMeasures3.json
- test/unit/ngsiv2/contextRequests/timestampMeasure.json
- test/unit/ngsiv2/contextRequests/timestampMeasure2.json
related https://github.com/telefonicaid/iotagent-node-lib/pull/1344
> align tests with metadata timestamp when timestamp is measure fix

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> Step: 2.0.0-next -> 2.1.0

- test/deviceProvisioning/provisionCommandBidirectional.json
- test/deviceProvisioning/provisionCommandBidirectionalWithUrl.json
- test/unit/ngsiv2/bidirectionalityHttp-test.js
This PR fix bidirectionality tests after https://github.com/telefonicaid/iotagent-node-lib/pull/1339
> Fix bidirectionality tests

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotajson.spec
> Step: 2.1.0-next -> 2.2.0

- package.json
> Step: 2.2.0 -> 2.2.0-next

- CHANGES_NEXT_RELEASE
- test/unit/ngsiv2/commandsPolling-test.js
> Changes in polling command test case file

- CHANGES_NEXT_RELEASE
- test/unit/ngsiv2/HTTP_commands_test.js
- test/unit/ngsiv2/HTTP_receive_measures-test3.js
- test/unit/ngsiv2/HTTP_reveice_measures-test.js
- test/unit/ngsiv2/HTTP_reveice_measures-test2.js
- test/unit/ngsiv2/MQTT_commands_test.js
- test/unit/ngsiv2/MQTT_receive_measures-test.js
- test/unit/ngsiv2/MQTT_receive_measures-test2.js
- test/unit/ngsiv2/amqpBinding-test.js
- test/unit/ngsiv2/amqpBinding-test2.js
- test/unit/ngsiv2/attribute-alias_test.js
- test/unit/ngsiv2/commandsAmqp-test.js
- test/unit/ngsiv2/commandsPolling-test.js
- test/unit/ngsiv2/configuration-api_test.js
- test/unit/ngsiv2/explicit_attributes-test.js
- test/unit/ngsiv2/subscription-management_test.js
related https://github.com/telefonicaid/iotagent-node-lib/pull/1386
> update patch -> post according default value for appendMode is true

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/advanced-issue-labeler.yml
- .github/workflows/issue-labeler.yml
Twin PR https://github.com/telefonicaid/iotagent-node-lib/pull/1379
> Add issue template

- CHANGES_NEXT_RELEASE
- test/unit/ngsiv2/HTTP_commands_test.js
- test/unit/ngsiv2/HTTP_get-configuration_test.js
- test/unit/ngsiv2/HTTP_receive_measures-test3.js
- test/unit/ngsiv2/HTTP_reveice_measures-test.js
- test/unit/ngsiv2/HTTP_reveice_measures-test2.js
- test/unit/ngsiv2/MQTT_commands_test.js
- test/unit/ngsiv2/MQTT_get-configuration_test.js
- test/unit/ngsiv2/MQTT_receive_measures-test.js
- test/unit/ngsiv2/MQTT_receive_measures-test2.js
- test/unit/ngsiv2/_subscription-management_test.js
- test/unit/ngsiv2/amqpBinding-test.js
- test/unit/ngsiv2/amqpBinding-test2.js
- test/unit/ngsiv2/attribute-alias_test.js
- test/unit/ngsiv2/commandsAmqp-test.js
- test/unit/ngsiv2/commandsPolling-test.js
- test/unit/ngsiv2/configuration-api_test.js
- test/unit/ngsiv2/explicit_attributes-test.js
related and needs https://github.com/telefonicaid/iotagent-node-lib/pull/1390
> remove initial entity from mocks

- package.json
> Step: 2.3.0 -> 2.3.0-next

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
related https://github.com/telefonicaid/iotagent-node-lib/issues/1430
> ensure apikey from measure/group in already provisioned device

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> step 2.3.0-next -> 2.4.0

- package.json
> step 2.4.0 -> 2.4.0-next

- lib/bindings/AMQPBinding.js
- lib/bindings/HTTPBinding.js
- lib/bindings/MQTTBinding.js
continuation of PR https://github.com/telefonicaid/iotagent-json/pull/762
Using the same CNR entry
> the same fix for http, mqtt and amqp bindings

- docs/usermanual.md
- test/unit/ngsiv2/HTTP_receive_ngsiv2_measures-test.js
- test/unit/ngsiv2/MQTT_receive_ngsiv2_measures-test.js
- test/unit/ngsiv2/contextRequests/ngsiv2PayloadMeasure.json
- test/unit/ngsiv2/contextRequests/ngsiv2PayloadMeasure2.json
related: https://github.com/telefonicaid/iotagent-json/pull/779
> add metadata to ngsiv2 payload example

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> step 2.3.0-next -> 3.0.0

- test/functional/functional-tests-runner.js
This PR fix skipping tests at should level (why now is not passing tests at master)
Twin PR: https://github.com/telefonicaid/iotagent-node-lib/pull/1535
> Fix skipping tests at should level

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> step 3.0.1 -> 3.1.0

- package.json
> step 3.0.0 -> 3.1.0-next

- docs/requirements.txt
See PR https://github.com/telefonicaid/fiware-orion/pull/4475
> FIX mkdocs version

- docs/usermanual.md
Remove extra code block characters
> Fix typo usermanual.md

- CHANGES_NEXT_RELEASE
Related PR https://github.com/telefonicaid/iotagent-json/pull/804#issuecomment-1914871013
> FIX improve CHANGES_NEXT_RELEASE

- package.json
>  step 3.2.0 -> 3.2.0-next

- docs/usermanual.md
PR adding doc: for https://github.com/telefonicaid/iotagent-json/pull/804
> Add NGSI patching type and id documentation

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
related and depends on https://github.com/telefonicaid/iotagent-node-lib/pull/1582
issue https://github.com/telefonicaid/iotagent-json/issues/815
> Include device info in errors

- CHANGES_NEXT_RELEASE
- lib/bindings/ARGOBinding.js
- test/unit/ngsiv2/ARGO_receive_measures-test.js
- test/unit/ngsiv2/argoMeasure.json
Adds support for internal SOAP service
> add argo binding

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> Task/prepare 3.3.0

- package.json
> step 3.3.0 -> 3.3.0-next

- package.json
> step 3.4.0 -> 3.4.0-next

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBinding.js
Fix for: https://github.com/telefonicaid/iotagent-json/issues/827
Needs https://github.com/telefonicaid/iotagent-node-lib/pull/1608
> fix bodyParser express limit from iota config

- CHANGES_NEXT_RELEASE
- lib/bindings/AMQPBinding.js
- lib/bindings/ARGOBinding.js
- lib/bindings/HTTPBinding.js
- lib/bindings/MQTTBinding.js
- lib/iotagent-json.js
- package.json
- test/unit/ngsiv2/HTTP_update_device_test.js
- test/unit/ngsiv2/deviceProvisioning/provisionDeviceHTTP4.json
- test/unit/ngsiv2/deviceProvisioning/updateProvisionDevice4.json
fix for issue https://github.com/telefonicaid/iotagent-json/issues/833
needs https://github.com/telefonicaid/iotagent-node-lib/pull/1616
> uses previous device in device update handler

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> prepare 3.5.0

- package.json
> step 3.5.0 -> 3.5.0-next

- package.json
> step 3.6.0 -> 3.6.0-next

- test/unit/ngsiv2/HTTP_reveice_measures-test.js
needs https://github.com/telefonicaid/iotagent-node-lib/pull/1691
> update test about lastMeasure and add test about oldCtxt in jexl usage

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
mimics https://github.com/telefonicaid/iotagent-json/pull/843
> step 3.6.0 -> 3.7.0

- package.json
> step 3.7.0 -> 3.7.0-next

- CHANGES_NEXT_RELEASE
- Changelog
- lib/bindings/HTTPBinding.js
fix for https://github.com/telefonicaid/iotagent-json/issues/863
> use code from status when available

- docs/requirements.txt
Mimics https://github.com/telefonicaid/iotagent-json/pull/850
> Bump jinja2 from 3.1.5 to 3.1.6 in /docs

- Changelog
- docs/usermanual.md
- lib/bindings/AMQPBinding.js
- lib/bindings/HTTPBinding.js
- lib/bindings/MQTTBinding.js
- lib/commandHandler.js
- test/deviceProvisioning/provisionCommandHTTP3.json
- test/deviceProvisioning/provisionCommandHTTP4.json
- test/unit/ngsiv2/HTTP_commands_test.js
Issue: https://github.com/telefonicaid/iotagent-json/issues/873
>  Task/add headers to http commands

- test/unit/ngsiv2/HTTP_commands_test.js
continuation of https://github.com/telefonicaid/iotagent-json/pull/874
> add test about group command with extra headers

- package.json
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/862
> step 3.8.0 -> 3.8.0-next

- CHANGES_NEXT_RELEASE
- lib/bindings/ARGOBinding.js
- lib/bindings/HTTPBinding.js
- lib/commonBindings.js
Related with reopen issue: https://github.com/telefonicaid/iotagent-node-lib/issues/1669
and needs https://github.com/telefonicaid/iotagent-node-lib/pull/1725
> fix lastMeasure stored: use original measure

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBinding.js
Needs: https://github.com/telefonicaid/iotagent-node-lib/pull/1724/
> ensure trust proxy in express

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/878
> step 3.8.0-next -> 3.9.0

- .github/workflows/ci.yml
- CHANGES_NEXT_RELEASE
- docker/Dockerfile
- docker/hooks/build
- docker/hooks/post_push
- package.json
Issue https://github.com/telefonicaid/iotagent-node-lib/issues/1730
> FIX node20 as minimum version

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> step 3.9.0-next -> 3.10-0
